version: 2
jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
      - run: (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build and check
          command: |
            echo "*** Building and checking $site ***"; 
            gem install -N jekyll-secinfo jekyll-last-modified-at
            ./update.sh
            # Removing some stubs
            rm -f _cves/CVE-3000-*
            rm -rf _cases/DIVD-3000-0000*
            jekyll build 2>&1| tee jekyll-build.log;
            ./proof_html.sh 
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/_site"

  upload:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install software
          command: |
            apk update;
            apk add rsync openssh;
            echo "set ftp:passive-mode true" > ~/.lftprc
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            4a:b2:60:17:4d:ff:27:80:68:5a:66:89:6f:bd:73:59
      - run:
          name: Upload
          command: |
            mkdir -p ~/.ssh;
            echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            cd /root/project/_site;
            rsync -av --delete . www-divd@upload.bit.nl:htdocs/csirt-divd-nl;
      - run:
          name: Trigger www build
          command: |
            apk add curl ;
            curl --location --request POST 'https://circleci.com/api/v2/project/github/DIVD-NL/web-www/pipeline' \
            --header 'Content-Type: application/json' \
            -u "${CIRCLE_CI_TOKEN}"

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - main