version: 2
jobs:

  build:
    docker:
      - image: mrseccubus/github-pages:latest
    steps:
      - run: (cd /root/;rm -rf project;mkdir project)
      - checkout
      - run:
          name: Build and check
          command: |
            for site in csirt.divd.nl www.divd.nl; do
              ( 
                echo "*** Building and checking $site ***"; 
                cd $site;
                gem install -N jekyll-secinfo jekyll-last-modified-at
                ./update.sh
                # Removing some stubs
                rm -f _cves/CVE-3000-*
                rm -rf _cases/DIVD-3000-0000*
                jekyll build 2>&1| tee jekyll-build.log;
                ./proof_html.sh 
              ) 
            done
      - save_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - "/root/project/www.divd.nl/_site"
            - "/root/project/csirt.divd.nl/_site"
            - "/root/project/.htaccess"


  upload:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: Install software
          command: |
            apk update;
            apk add rsync openssh;
            echo "set ftp:passive-mode true" > ~/.lftprc
      - restore_cache:
          key: jekyll-{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys:
          fingerprints:
            4a:b2:60:17:4d:ff:27:80:68:5a:66:89:6f:bd:73:59
      - run:
          name: Upload
          command: |
            mkdir -p ~/.ssh;
            echo  "upload.bit.nl,213.136.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIVx+0N0LECcGHPywPCk9uz4/l3kNUVNe5QQRleIkMCTarkYauvRrPNPl49x3LIjF6cZsmQZX7jwgsJqEzfcF98=" > ~/.ssh/known_hosts;
            cd /root/project/;
            rsync -av .htaccess www-divd@upload.bit.nl:htdocs;
            cd /root/project/csirt.divd.nl/_site;
            rsync -av --delete . www-divd@upload.bit.nl:htdocs/csirt-divd-nl;
            rsync -av --delete .well-known www-divd@upload.bit.nl:htdocs/csirt-divd-nl/.well-known;
            cd /root/project/www.divd.nl/_site;
            rsync -av "--exclude=data/*" --delete . www-divd@upload.bit.nl:htdocs/divd-nl;
            rsync -av --delete .well-known www-divd@upload.bit.nl:htdocs/divd-nl/.well-knonw;

workflows:
  version: 2
  build_and_upload:
    jobs:
      - build
      - upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master