name: build_test_deploy
run-name: Build, test and deploy website (if needed)
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' 
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Update external content
        run:  ./update.sh
      - name: Clean up stubs
        run:  rm -rf _cases/3000 _cves/CVE-3000-*
      - name: Build
        run:  MAKE="make -j4" bundle install --jobs=4 && bundle exec jekyll build  --future 2>&1 | tee jekyll-build.log
      - name: install prerequisites
        run:  pip3 install html5validator && gem install --no-document html-proofer
      - name: Test HTML code
        run:  ./proof_html.sh
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v3
        if:   ${{ github.ref == 'refs/heads/main' }}
        with:
          name: html
          path: _site/**
          retention-days: 1
  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: "github.ref == 'refs/heads/main'"
    steps:
      - name: Download html
        uses: actions/download-artifact@v3
        with:
          name: html
      - run: ls
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: .
          remote_path: htdocs/csirt-divd-nl
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY_CSIRT }}
